version: '3.9'
services:
  postgresql:
    image: postgres:13.3-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres-vulder:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:5.5
    ports:
      - 88:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@example.com
      - PGADMIN_DEFAULT_PASSWORD=test
volumes:
  postgres-vulder:
    external: true