version: '3.9'
services:
  postgresql:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres-vulder:/var/lib/postgresql/data
volumes:
  postgres-vulder:
    external: true